version: '3.4'
services:
    api_base: &api_base
        env_file: server/.env
        build:
            context: .
            dockerfile: server/Dockerfile
            target: development
        command: [
            "./node_modules/.bin/nodemon",
            "--watch",
            "lib",
            "--watch",
            "migrations",
            "--watch",
            "server",
            "server/index.js"
        ]
        environment:
            - NODE_ENV=development
        ports:
            - 3000:3000
    api:
        env_file: server/.env
        # hack for docker-compose v3 dropping `extends` support
        << : *api_base
        # allows for hot-reloading of server
        volumes:
            - ./lib:/app/lib
            - ./server:/app/server
            - ./migrations:/app/migrations
            - ./test:/app/test
            - ./package.json:/app/package.json
    test_base: &test_base
        env_file: server/test.env
        build:
            context: .
            dockerfile: server/Dockerfile
            target: test
    test:
        env_file: server/test.env
        # hack for docker-compose v3 dropping `extends` support
        << : *test_base
        # allows for hot-reloading of server
        volumes:
            - ./lib:/app/lib
            - ./server:/app/server
            - ./test:/app/test
            - ./package.json:/app/package.json
    postgres:
        env_file: server/.env
        image: postgres:9.6-alpine
        ports: 
            - "5432:5432"
    unleash:
        env_file: server/.env
        image: unleashorg/unleash-server
        ports:
            - "4242:4242"
        depends_on:
            - postgres
        command: npm run start
