DROP TABLE "account";
DROP TABLE "user";
DROP TABLE "user_role";
DROP TABLE "reset_token";
DROP TABLE "api_token";
DROP TABLE "api_auth_role";
DROP TABLE "api_auth_permission";
DROP TABLE "api_token__api_auth_role";
DROP TABLE "user_role__api_auth_role";